
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shalomeliy/main_score:${IMAGE_VERSION}
    ports:
      - "8777:5000"
    volumes:
      - "./scores.txt:/scores.txt"
