version: '3.8'

services:
  flask-app:
    image: "shalomeliy/main_score:${IMAGE_VERSION:-latest}"  # Use IMAGE_VERSION, default to 'latest' if not set
    ports:
      - "8777:5000"
    volumes:
      - "./scores.txt:/scores.txt"
