version: '3.8'


services:
  flask-app:
    image: #main_score:1.0
    build: .
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - "./scores.txt:/scores.txt"
